# ------------------ Tarefa 1 ------------------------------------------

research_task:
  description: >
    Faça uma pesquisa completa sobre {topic}
    Certifique-se de encontrar informações interessantes e relevantes, considerando que
    o ano atual é {current_year}.
  expected_output: >
    Uma lista com 10 tópicos com as informações mais relevantes sobre {tópico}
  agent: researcher

# ----------------------------------------------------------------------------------------
# ------------------------------------- Tarefa 2  ----------------------------------------
reporting_task:
  description: >
    Revise o contexto obtido e expanda cada tópico em uma seção completa para um relatório.
    Certifique-se de que o relatório seja detalhado e contenha todas as informações relevantes.

  expected_output: >
    Um relatório completo com os tópicos principais, cada um com uma seção completa de informações.
    Formatado em markdown sem '```'
  agent: reporting_analyst
